version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    env_file:
      - "./.env"
    networks:
      - back
  
  wordpress:
    depends_on:
        - db
    image: wordpress:4.9.4 
    restart: always
    volumes: 
      - ./wordpress:/var/www/html
      - ./wordpress/wp-content/uploads:/var/www/html/wp-content/uploads
      - ./wordpress/wp-content/uploads:/var/www/html/wp-content/mu-plugins
      - ./wordpress/wp-content/uploads:/var/www/html/wp-content/plugins/advanced-custom-fields
      - ./wordpress/wp-content/themes/simple:/var/www/html/wp-content/themes/simple
      - ./wordpress/wp-content/themes/simple:/var/www/html/wp-content/themes/simpleII
      - ./wordpress/wp-content/themes/simple:/var/www/html/wp-content/themes/mockedutheme
    env_file:
      - "./.env"
    ports:
      - "8000:80"
    networks:
      - back
  
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports: 
      - "8083:80"
    env_file:
      - "./.env"
    networks:
      - back

networks:
  back:
volumes:
  db_data:
  